update chat_channel_type set channel_type_name = "私聊" where channel_type_code = 1;
update chat_channel_type set channel_type_name = "轻聊" where channel_type_code = 2;
update chat_channel_type set channel_type_name = "队伍" where channel_type_code = 3;
update chat_channel_type set channel_type_name = "好友" where channel_type_code = 4;
update chat_channel_type set channel_type_name = "国家" where channel_type_code = 12;
update chat_channel_type set channel_type_name = "家族" where channel_type_code = 14;
update chat_channel_type set channel_type_name = "世界" where channel_type_code = 26;
update chat_channel_type set channel_type_name = "区域" where channel_type_code = 47;
update chat_channel_type set channel_type_name = "主播" where channel_type_code = 48;